

# This file was *autogenerated* from the file census.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_8 = Integer(8); _sage_const_16 = Integer(16); _sage_const_32 = Integer(32); _sage_const_0 = Integer(0)# Census of Galois 2-group Belyi maps oriented toward the nonsolvability question.
#
# Each isomorphism class = an epimorphism  phi: F_2 ->> G  (G a 2-group of order d),
# up to Aut(G), given by GQuotients. From phi we read the monodromy triple
#   s0 = phi(x), s1 = phi(y), sinf = (s0 s1)^{-1}
# with local ramification orders e0,e1,einf = orders of s0,s1,sinf in the regular rep.
# Genus (Riemann-Hurwitz, Galois cover X -> X/G = P^1 branched at {0,1,inf}):
#   g = 1 + (|G|/2)*(1 - 1/e0 - 1/e1 - 1/einf).
#
# For J[2] = H^1(X,F_2) to have a NONSOLVABLE Galois image we need g>=2
# (Sp_2(F_2)=S_3 solvable; Sp_4(F_2)=S_6 nonsolvable) AND, since the Galois
# image centralizes rho(G) in Sp_{2g}(F_2), the group G must be nonabelian and
# act on J[2] with a large centralizer.  Here we tabulate g and abelianness so we
# know where the candidates live.  (The centralizer test itself is Stage 2.)
import sys
from collections import Counter

F = libgap.FreeGroup(_sage_const_2 )
gens = libgap.GeneratorsOfGroup(F)

degrees = [int(x) for x in sys.argv[_sage_const_1 :]] or [_sage_const_2 ,_sage_const_4 ,_sage_const_8 ,_sage_const_16 ,_sage_const_32 ]
for d in degrees:
    n = int(libgap.NrSmallGroups(d))
    total = _sage_const_0 
    genus_counter = Counter()          # genus -> #triples
    genus_nonab = Counter()            # genus -> #triples with G nonabelian
    candidates = []                    # (genus, G id, structure, e0,e1,einf, abelian?)
    for i in range(_sage_const_1 , n+_sage_const_1 ):
        G = libgap.SmallGroup(d, i)
        ab = bool(libgap.IsAbelian(G))
        gid = f"[{d},{i}]"
        try:
            struct = str(libgap.StructureDescription(G))
        except Exception:
            struct = "?"
        q = libgap.GQuotients(F, G)
        for h in q:
            total += _sage_const_1 
            s0 = libgap.Image(h, gens[_sage_const_0 ])
            s1 = libgap.Image(h, gens[_sage_const_1 ])
            sinf = (s0*s1)**(-_sage_const_1 )
            e0 = int(libgap.Order(s0)); e1 = int(libgap.Order(s1)); ei = int(libgap.Order(sinf))
            g = _sage_const_1  + (d/_sage_const_2 )*(_sage_const_1  - _sage_const_1 /e0 - _sage_const_1 /e1 - _sage_const_1 /ei)
            g = int(g)
            genus_counter[g] += _sage_const_1 
            if not ab:
                genus_nonab[g] += _sage_const_1 
            if g >= _sage_const_2  and not ab:
                candidates.append((g, gid, struct, (e0,e1,ei)))
    print(f"===== degree d = {d}  ({total} triples) =====")
    print("  genus:  " + "  ".join(f"g{g}:{genus_counter[g]}" for g in sorted(genus_counter)))
    print("  of which G nonabelian: " +
          "  ".join(f"g{g}:{genus_nonab[g]}" for g in sorted(genus_nonab) if genus_nonab[g]))
    # show the lightest candidates (smallest |G| already fixed = d; sort by genus then structure)
    cand_by = {}
    for g, gid, struct, ram in candidates:
        cand_by.setdefault((struct,), []).append((g, ram))
    print(f"  nonabelian G with genus>=2: {len(candidates)} triples, "
          f"{len(set(c[_sage_const_1 ] for c in candidates))} distinct groups")
    seen = set()
    for g, gid, struct, ram in sorted(candidates):
        key = (struct, g)
        if key in seen: continue
        seen.add(key)
        print(f"    g={g}  G={gid} {struct:20s} ram(e0,e1,inf)={ram}")
    print(flush=True)

