

# This file was *autogenerated* from the file count_triples.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_7 = Integer(7); _sage_const_8 = Integer(8); _sage_const_19 = Integer(19); _sage_const_16 = Integer(16); _sage_const_55 = Integer(55); _sage_const_32 = Integer(32); _sage_const_151 = Integer(151); _sage_const_64 = Integer(64); _sage_const_503 = Integer(503); _sage_const_128 = Integer(128); _sage_const_1799 = Integer(1799); _sage_const_256 = Integer(256); _sage_const_7175 = Integer(7175); _sage_const_0 = Integer(0)# Replicate Thm 1.2.2 of Musty's thesis: number of isomorphism classes of
# (Galois) 2-group Belyi maps of degree d = # normal subgroups of index d in F_2
#   = sum over 2-groups G of order d of #{ Aut(G)-orbits of generating pairs }
#   = sum_i  |GQuotients(F_2, SmallGroup(d,i))|
import sys, time

F = libgap.FreeGroup(_sage_const_2 )
expected = {_sage_const_1 :_sage_const_1 , _sage_const_2 :_sage_const_3 , _sage_const_4 :_sage_const_7 , _sage_const_8 :_sage_const_19 , _sage_const_16 :_sage_const_55 , _sage_const_32 :_sage_const_151 , _sage_const_64 :_sage_const_503 , _sage_const_128 :_sage_const_1799 , _sage_const_256 :_sage_const_7175 }

degrees = [int(x) for x in sys.argv[_sage_const_1 :]] or [_sage_const_1 ,_sage_const_2 ,_sage_const_4 ,_sage_const_8 ,_sage_const_16 ,_sage_const_32 ]
for d in degrees:
    t0 = time.time()
    n = int(libgap.NrSmallGroups(d))
    total = _sage_const_0 
    two_gen = _sage_const_0 
    for i in range(_sage_const_1 , n+_sage_const_1 ):
        G = libgap.SmallGroup(d, i)
        q = libgap.GQuotients(F, G)
        c = int(libgap.Length(q))
        if c > _sage_const_0 :
            two_gen += _sage_const_1 
        total += c
    exp = expected.get(d, "?")
    ok = "OK" if exp == total else "MISMATCH"
    print(f"d={d:4d}  groups={n:6d}  2-generated={two_gen:4d}  "
          f"triples={total:6d}  expected={exp:>5}  [{ok}]  {time.time()-t0:6.1f}s",
          flush=True)

