

# This file was *autogenerated* from the file tests/test_towers.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_7 = Integer(7); _sage_const_2 = Integer(2); _sage_const_4 = Integer(4); _sage_const_8 = Integer(8)# Tests for belyi/towers.sage (M3 part 1: absolute-model square-root composition).
load("belyi/towers.sage"); load("belyi/verify.sage")
from sage.all import GF, PolynomialRing, FunctionField

PASS = _sage_const_0 ; FAIL = _sage_const_0 
def check(name, fn):
    global PASS, FAIL
    try:
        fn(); print(f"  ok   {name}"); PASS += _sage_const_1 
    except Exception as e:
        print(f"  FAIL {name}: {e}"); FAIL += _sage_const_1 

def base_ring(p):
    K = FunctionField(GF(p), 'x'); return K, K.gen(), PolynomialRing(K, 'y').gen()

# sqrt(y) over y^2=x(x-1)  ==  z^4 = x(x-1)  (C4, genus1, passport (4,4,2))
def c4():
    K, x, y = base_ring(_sage_const_7 )
    Q = compose_sqrt(K, y**_sage_const_2  - x*(x-_sage_const_1 ), y)
    L = K.extension(Q, 'w')
    r = verify_belyi(L, x, expected_passport=(_sage_const_4 , _sage_const_4 , _sage_const_2 ), expected_genus=_sage_const_1 , name="C4")
    assert L.degree() == _sage_const_4 

# two more square roots of x -> w^8 = x (C8, genus 0, ramified only 0,oo)
def c8():
    K, x, y = base_ring(_sage_const_7 )
    Q2 = compose_sqrt(K, y**_sage_const_2  - x, y)                 # z^4 = x
    z = Q2.parent().gen()
    Q3 = compose_sqrt(K, Q2, z)                        # w^8 = x
    L = K.extension(Q3, 'w')
    assert L.degree() == _sage_const_8  and L.genus() == _sage_const_0 
    r = verify_belyi(L, x, name="C8")
    assert tuple(sorted(r['passport'])) == (_sage_const_1 , _sage_const_8 , _sage_const_8 )

for nm, fn in [("compose C4", c4), ("compose C8", c8)]:
    check(nm, fn)
print(f"\n{PASS} passed, {FAIL} failed")

