

# This file was *autogenerated* from the file tests/test_cyclic.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_7 = Integer(7); _sage_const_4 = Integer(4); _sage_const_16 = Integer(16); _sage_const_8 = Integer(8); _sage_const_5 = Integer(5); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2)# Tests for belyi/cyclic.sage (M2), verified through belyi/verify.sage (M1).
load("belyi/verify.sage")
load("belyi/cyclic.sage")
from sage.all import GF, Infinity

PASS = _sage_const_0 ; FAIL = _sage_const_0 
def check(name, fn):
    global PASS, FAIL
    try:
        fn(); print(f"  ok   {name}"); PASS += _sage_const_1 
    except Exception as e:
        print(f"  FAIL {name}: {e}"); FAIL += _sage_const_1 

# C16 y^16 = (x-1)  (thesis oracle f16T1-1,16,16-g0, up to unit): passport (1,16,16) genus 0
def c16():
    L, x, f = cyclic_absolute(GF(_sage_const_7 ), _sage_const_4 , _sage_const_0 , _sage_const_1 )
    r = verify_belyi(L, x, expected_passport=(_sage_const_1 , _sage_const_16 , _sage_const_16 ), expected_genus=_sage_const_0 , name="C16")
    assert cyclic_passport(_sage_const_4 , _sage_const_0 , _sage_const_1 ) == (_sage_const_1 , _sage_const_16 , _sage_const_16 ), cyclic_passport(_sage_const_4 , _sage_const_0 , _sage_const_1 )

# C16 y^16 = x(x-1): predicted passport (16,16,8); confirm Belyi + passport formula matches verifier
def c16_ab():
    L, x, f = cyclic_absolute(GF(_sage_const_7 ), _sage_const_4 , _sage_const_1 , _sage_const_1 )
    r = verify_belyi(L, x, name="C16 x(x-1)")
    assert tuple(sorted(r['passport'])) == tuple(sorted(cyclic_passport(_sage_const_4 , _sage_const_1 , _sage_const_1 ))),         (r['passport'], cyclic_passport(_sage_const_4 , _sage_const_1 , _sage_const_1 ))
    assert cyclic_passport(_sage_const_4 , _sage_const_1 , _sage_const_1 ) == (_sage_const_16 , _sage_const_16 , _sage_const_8 )

# C8 y^8 = x^3(x-1): passport formula vs verifier, and genus consistency
def c8():
    L, x, f = cyclic_absolute(GF(_sage_const_5 ), _sage_const_3 , _sage_const_3 , _sage_const_1 )
    r = verify_belyi(L, x, name="C8 x^3(x-1)")
    assert tuple(sorted(r['passport'])) == tuple(sorted(cyclic_passport(_sage_const_3 , _sage_const_3 , _sage_const_1 )))

# C4 y^4 = x(x-1): passport (4,4,2)
def c4():
    L, x, f = cyclic_absolute(GF(_sage_const_3 ), _sage_const_2 , _sage_const_1 , _sage_const_1 )
    r = verify_belyi(L, x, expected_passport=(_sage_const_4 , _sage_const_4 , _sage_const_2 ), name="C4 x(x-1)")

for nm, fn in [("C16 (1,16,16)", c16), ("C16 x(x-1)", c16_ab),
               ("C8 x^3(x-1)", c8), ("C4 x(x-1)", c4)]:
    check(nm, fn)
print(f"\n{PASS} passed, {FAIL} failed")

