// Offline moduli-field verdict for the k=4 genus-2 corner: the
// (2@0, 8@phi, 8@phi^3) passport of PGammaL(2,16), Ni = 12 (script 31).
//
// Input: the recognition-stage dump written by 31_g2_local.m with
// BELYI_DUMP_CFS set (recognition.m genus-2 block), which defines
//     curve_coeffs, u, denom_coeffs, num_coeffs
// at full working precision.  The hyperelliptic model there is
//     y^2 + U(t) y = V(t),
//     V = -sum_{i=0}^{2g+2} curve_coeffs[i+1] t^i,
//     U = -sum_{i=0}^{g+1}  curve_coeffs[2g+4+i] t^i,      g = 2.
//
// We recognize the ABSOLUTE Igusa invariants, which are gauge-invariant
// (independent of the GL_2 coordinate choice and of the y-scaling that the
// numerical solver fixes arbitrarily) -- the genus-2 analogue of the
// j-invariant route of 26_g1_field.m.  Discipline, strengthened past 12/26:
// fit at a LADDER of LLL precisions and demand the same minimal polynomial at
// the top three, then verify the residual at full precision.  A spurious fit
// saturates the lattice and its height grows like 10^(P/(d+1)), linearly in
// the precision P; a genuine one stops moving.  Watching that growth is what
// a single height threshold cannot do -- on the pre-Newton coefficients of
// rep 1, every degree from 1 to 12 grew linearly, i.e. pure noise.
//
// Verdict: the field generated by the absolute invariants is the moduli
// field of the curve.  The question is whether it again meets the universal
// degree-8 field K (disc 2^18 * 5^2 * 17) of README.md.

SetColumns(0);

dumpfile := GetEnv("BELYI_G2_DUMP");
if dumpfile eq "" then dumpfile := "out/g2_rep1_cfs.m"; end if;
printf "loading %o\n", dumpfile;
// `load` needs a literal filename, so read and eval instead (this also keeps
// the dump's other variables out of the way).
dumptext := Read(dumpfile);
curve_coeffs := eval (dumptext cat "\nreturn curve_coeffs;");

g := 2;
CC := Parent(curve_coeffs[1]);
prec := Precision(CC);
printf "dump precision: %o digits, %o curve coefficients\n", prec, #curve_coeffs;
assert #curve_coeffs ge 2*g+4+g+1;

Rt<t> := PolynomialRing(CC);
V := Rt!0; U := Rt!0;
for i in [0..2*g+2] do V -:= curve_coeffs[i+1]*t^i; end for;
for i in [0..g+1]   do U -:= curve_coeffs[2*g+4+i]*t^i; end for;
printf "deg V = %o, deg U = %o\n", Degree(V), Degree(U);

// complete the square: y^2 + U y = V  <->  (y + U/2)^2 = V + U^2/4
f := V + U^2/4;
printf "deg f = %o\n", Degree(f);

IC := IgusaClebschInvariants(f);
I2, I4, I6, I10 := Explode(IC);
printf "|I2| = 1e%o, |I4| = 1e%o, |I6| = 1e%o, |I10| = 1e%o\n",
    Round(Log(10, Max(Abs(I2), 10^-9999))), Round(Log(10, Max(Abs(I4), 10^-9999))),
    Round(Log(10, Max(Abs(I6), 10^-9999))), Round(Log(10, Max(Abs(I10), 10^-9999)));
if Abs(I10) lt 10^(-prec div 2) then
    printf "FAIL|I10 vanishes numerically: the model is singular (not a genus-2 curve)\n";
    quit;
end if;

// Absolute (weight-zero) invariants.  The classical triple degenerates when
// I2 vanishes, so fall back to an I2-free generating set in that case.
// NB: use the LOW-WEIGHT ratios I4/I2^2, I6/I2^3, I10/I2^5 rather than the
// classical i1 = I2^5/I10 etc.  They generate the same field, but the
// classical triple is a weight-30 combination of the curve coefficients and
// its minimal polynomials have heights ~1e22 at degree 12, which 285 digits
// cannot certify; the ratios below are weight 4-10 and far better conditioned.
if Abs(I2) gt 10^(-prec div 4) * Max(1, Abs(I4)) then
    absinvs := [ I4/I2^2, I6/I2^3, I10/I2^5 ];
    names := [ "I4/I2^2", "I6/I2^3", "I10/I2^5" ];
else
    printf "note: I2 is numerically zero; using the I2-free absolute invariants\n";
    absinvs := [ I4^5/I10^2, I6^5/I10^3, I4*I6/I10 ];
    names := [ "I4^5/I10^2", "I6^5/I10^3", "I4*I6/I10" ];
end if;

// Recognition with the 12/26 discipline.
degs := [1,2,3,4,6,8,12];        // Ni = 12 bounds the Galois orbit
// The dumped coefficients carry ~prec digits with a noise floor near
// 10^-(prec-10); the Igusa invariants lose some of that to amplification, so
// run LLL well inside the usable range and verify against the full precision.
precL := Floor(0.8*prec);         // top of the LLL precision ladder
CCL := ComplexField(precL);
QR<zz> := PolynomialRing(Rationals());

// The decisive test is how the fitted height behaves as LLL precision rises.
// A spurious fit always saturates the lattice: its height grows like
// 10^(P/(d+1)), linearly in P.  A genuine minimal polynomial locks onto a
// fixed height once P exceeds d*log10(height) and stops moving.  So we fit at
// a ladder of precisions and demand the SAME polynomial at the top three --
// far more informative than any single height threshold.
ladder := [ Floor(0.4*prec), Floor(0.55*prec), Floor(0.7*prec), precL ];

function RecognizeInv(z, nm)
    for d in degs do
        fits := [ PowerRelation(ComplexField(P)!z, d : Al := "LLL") : P in ladder ];
        hts := [ Degree(p) lt 1 select 0 else
                 Round(Log(10, Max([ Abs(cf) : cf in Coefficients(p) ]))) : p in fits ];
        pol := fits[#fits];
        dd := Degree(pol);
        if dd lt 1 then continue; end if;
        top := { QR!fits[i] : i in [#fits-2..#fits] };
        if #top ne 1 then
            printf "  %o deg %o: heights %o across precisions %o -- noise, rejected\n",
                nm, d, hts, ladder;
            continue;
        end if;
        ht := Max([ Abs(cf) : cf in Coefficients(pol) ]);
        // residual at full precision
        resid := Abs(Evaluate(PolynomialRing(CC)!pol, z));
        scale := ht * Max(1, Abs(z))^dd;
        // the stability ladder above is the real discriminator; this is a
        // sanity check, so allow for error amplification through the invariants
        if resid lt scale * 10^(-Floor(0.6*prec)) then
            printf "  RECOGNIZED %o: degree %o, height ~1e%o\n",
                nm, dd, Round(Log(10, ht));
            return true, pol;
        else
            printf "  %o deg %o: verification failed (resid 1e%o vs scale 1e%o)\n",
                nm, d, Round(Log(10, Max(resid, 10^-9999))), Round(Log(10, scale));
        end if;
    end for;
    return false, QR!0;
end function;

printf "\nrecognizing absolute Igusa invariants (LLL ladder %o, verify at %o)\n",
    ladder, prec;
pols := [];
allfound := true;
for i in [1..#absinvs] do
    printf "%o = %o\n", names[i], ComplexField(30)!absinvs[i];
    ok, pol := RecognizeInv(absinvs[i], names[i]);
    if ok then
        Append(~pols, pol);
    else
        allfound := false;
        printf "  NOT RECOGNIZED: %o\n", names[i];
    end if;
end for;

if not allfound then
    printf "\nFAIL|some absolute invariant was not recognized at this precision\n";
    printf "MARKER|g2_field_incomplete\n";
    quit;
end if;

// The moduli field: the compositum of the invariant fields.
printf "\nmoduli field:\n";
flds := [];
for pol in pols do
    fp := QR!pol; fp /:= LeadingCoefficient(fp);
    fp := Factorization(fp)[1][1];   // the invariant is one root
    if Degree(fp) eq 1 then continue; end if;
    Append(~flds, NumberField(fp));
end for;

if #flds eq 0 then
    printf "all absolute invariants are RATIONAL: moduli field = Q\n";
    printf "VERDICT|moduli field Q, unramified everywhere -- no obstruction here\n";
    printf "MARKER|g2_field_done\n";
    quit;
end if;

M := flds[1];
for i in [2..#flds] do
    M := Compositum(M, flds[i]);
end for;
M := OptimizedRepresentation(AbsoluteField(M));
printf "degree %o, defining polynomial %o\n", Degree(M), DefiningPolynomial(M);
dM := Discriminant(Integers(M));
printf "discriminant factorization: %o\n", Factorization(dM);
printf "ramified primes: %o\n", [ p[1] : p in Factorization(dM) ];

// Comparison with the universal degree-8 moduli field K of README.md.
K := NumberField(QR!(zz^8 + 4*zz^7 + 4*zz^6 + 2*zz^4 + 12*zz^3 + 20*zz^2 + 8*zz + 2));
printf "\nuniversal K: disc %o\n", Factorization(Discriminant(Integers(K)));
isoKM := IsIsomorphic(M, K);
printf "M isomorphic to K: %o\n", isoKM;
if not isoKM then
    sub := #Subfields(K, Degree(M)) gt 0
        select exists{ S : S in Subfields(K, Degree(M)) | IsIsomorphic(S[1], M) }
        else false;
    printf "M is a subfield of K: %o\n", sub;
    subs := exists{ S : S in Subfields(M, Degree(K)) | IsIsomorphic(S[1], K) };
    printf "K is a subfield of M: %o\n", subs;
end if;

if Set([ p[1] : p in Factorization(dM) ]) subset {2} then
    printf "VERDICT|ONLY-2-RAMIFIED moduli field -- the corner does NOT close\n";
else
    printf "VERDICT|moduli field ramified outside 2 -- the corner closes\n";
end if;
printf "MARKER|g2_field_done\n";
quit;
