// One lane of the parallel Hecke-orbit computation.
//
// Each lane recomputes T(p_31^1) to define the two 8-dimensional simple
// components, then restricts T(p_31^i) and T(p_97^i) to those components.
//
// Required environment:
//   HMF_ROOT=/path/to/hilbertmodularforms
//   ORBIT_INDEX=1,...,8

SetColumns(0);

hmf_root := GetEnv("HMF_ROOT");
index_text := GetEnv("ORBIT_INDEX");
if hmf_root eq "" then
    error "Set HMF_ROOT to the pinned hilbertmodularforms checkout";
end if;
if index_text eq "" then
    error "Set ORBIT_INDEX to an integer from 1 through 8";
end if;
orbit_index := StringToInteger(index_text);
if orbit_index notin [1..8] then
    error "ORBIT_INDEX must be an integer from 1 through 8";
end if;
AttachSpec(hmf_root cat "/spec");

function RestrictMatrix(matrix, subspace)
    field := BaseRing(matrix);
    return Matrix(
        field,
        [Coordinates(subspace, vector*matrix) : vector in Basis(subspace)]
    );
end function;

function MatrixAsPolynomial(generator_matrix, target_matrix, polynomial_ring)
    field := BaseRing(generator_matrix);
    dimension := Nrows(generator_matrix);
    powers := [IdentityMatrix(field, dimension)];
    for exponent in [1..dimension-1] do
        Append(~powers, powers[#powers]*generator_matrix);
    end for;

    coefficient_space := VectorSpace(field, dimension);
    for coefficients in coefficient_space do
        candidate := ZeroMatrix(field, dimension, dimension);
        for exponent in [0..dimension-1] do
            if coefficients[exponent+1] ne 0 then
                candidate +:= coefficients[exponent+1]*powers[exponent+1];
            end if;
        end for;
        if candidate eq target_matrix then
            return &+[
                polynomial_ring!(coefficients[exponent+1])
                    *polynomial_ring.1^exponent
                : exponent in [0..dimension-1]
            ];
        end if;
    end for;
    error "Target Hecke matrix is not generated by the reference operator";
end function;

function FrobeniusOrder(trace)
    field := Parent(trace);
    companion := Matrix(field, 2, 2, [0, 1, 1, trace]);
    return Order(companion);
end function;

Qx<x> := PolynomialRing(Rationals());
F<beta> := NumberField(x^8 - 8*x^6 + 20*x^4 - 16*x^2 + 2);
OF := Integers(F);
sigma := hom< F -> F | -beta^3 + 3*beta >;

g31_orbit := [F![1, 2, 0, -4, 0, 1, 0, 0]];
g97_orbit := [F![1, -12, -4, 19, 1, -8, 0, 1]];
for i in [2..8] do
    Append(~g31_orbit, sigma(g31_orbit[#g31_orbit]));
    Append(~g97_orbit, sigma(g97_orbit[#g97_orbit]));
end for;
p31 := [ideal<OF | OF!generator> : generator in g31_orbit];
p97 := [ideal<OF | OF!generator> : generator in g97_orbit];
assert &and[IsPrime(prime) and Norm(prime) eq 31 : prime in p31];
assert &and[IsPrime(prime) and Norm(prime) eq 97 : prime in p97];

M := HilbertCuspForms(F, 1*OF, [2 : i in [1..8]]);
assert Dimension(M) eq 57;

F2 := GF(2);
F2t<t> := PolynomialRing(F2);
q1 := t^8 + t^4 + t^3 + t + 1;
q2 := t^8 + t^6 + t^5 + t^2 + 1;
assert IsIrreducible(q1) and IsIrreducible(q2);

reference_raw := InternalHMFRawHeckeDefinite(M, p31[1]);
reference := ChangeRing(reference_raw, F2);
component_1 := Nullspace(Evaluate(q1, reference));
component_2 := Nullspace(Evaluate(q2, reference));
assert Dimension(component_1) eq 8;
assert Dimension(component_2) eq 8;
reference_1 := RestrictMatrix(reference, component_1);
reference_2 := RestrictMatrix(reference, component_2);
assert CharacteristicPolynomial(reference_1) eq q1;
assert CharacteristicPolynomial(reference_2) eq q2;

K1<a1> := ext<F2 | q1>;
K2<a2> := ext<F2 | q2>;

procedure AnalyzePrime(rational_prime, index, prime_ideal)
    raw_operator := index eq 1 and rational_prime eq 31
        select reference_raw
        else InternalHMFRawHeckeDefinite(M, prime_ideal);
    operator := ChangeRing(raw_operator, F2);
    assert reference*operator eq operator*reference;

    operator_1 := RestrictMatrix(operator, component_1);
    operator_2 := RestrictMatrix(operator, component_2);
    polynomial_1 := MatrixAsPolynomial(reference_1, operator_1, F2t);
    polynomial_2 := MatrixAsPolynomial(reference_2, operator_2, F2t);
    trace_1 := Evaluate(polynomial_1, a1);
    trace_2 := Evaluate(polynomial_2, a2);
    order_1 := FrobeniusOrder(trace_1);
    order_2 := FrobeniusOrder(trace_2);

    if rational_prime eq 31 then
        assert Sort([order_1, order_2]) eq [255, 257];
    else
        assert Sort([order_1, order_2]) eq [51, 257];
    end if;

    printf "TRACE|%o|%o|q1|%o|%o\n",
        rational_prime, index, polynomial_1, order_1;
    printf "TRACE|%o|%o|q2|%o|%o\n",
        rational_prime, index, polynomial_2, order_2;
end procedure;

AnalyzePrime(31, orbit_index, p31[orbit_index]);
AnalyzePrime(97, orbit_index, p97[orbit_index]);
printf "PASS|constituent_orbit|%o\n", orbit_index;
