// Delta' pipeline prototype, validated on a small level over Q exactly.
//
// Goal: exercise every step of the Delta' computation (gate5-delta-prime-plan.md)
// on a level small enough to do over Q in one session, so the q0 multimodular
// run is only launched once the mechanics are known correct:
//   1. the raw (Big) operators and InnerProductMatrixBig share a basis;
//   2. on the NEW subspace the degeneracy/boundary vanishes -- checked here as
//      "new is W-orthogonal to old", i.e. the mass pairing sees new forms as a
//      clean sublattice of the character lattice;
//   3. the g-isotypic sublattice L_g saturates and its mass-Gram matrix Gamma
//      is integral and positive definite;
//   4. the sub/quotient determinant pair and the normalisation N(L)^2 * D_H.
//
// Env: HMF_ROOT; G3_LEVEL (rational prime, default 31); G3_MEMCAP (GB).
SetColumns(0);
memcap := GetEnv("G3_MEMCAP");
if memcap ne "" then SetMemoryLimit(StringToInteger(memcap)*1024^3); end if;
AttachSpec(GetEnv("HMF_ROOT") cat "/spec");
SetClassGroupBounds("GRH");
Qx<x> := PolynomialRing(Rationals());
F<b> := NumberField(x^8 - 8*x^6 + 20*x^4 - 16*x^2 + 2);
OF := Integers(F);
Zz<z> := PolynomialRing(Integers());
lev := GetEnv("G3_LEVEL"); if lev eq "" then lev := "31"; end if;
ln := StringToInteger(lev);
q := [ p[1] : p in Factorization(ln*OF) | Norm(p[1]) eq ln ][1];
printf "DP|level norm %o\n", Norm(q);

// --- raw ambient at level q, weight 2 ---
M := HilbertCuspForms(F, q, [2 : i in [1..8]]);
Mraw := M;  // we drive everything through the Big/raw operators
IP := InnerProductMatrixBig(M);
assert IsDiagonal(IP);
W := [ Integers()! IP[i,i] : i in [1..Nrows(IP)] ];
N := #W;
printf "DP|raw dim N = %o ; masses: distinct %o, max %o, lcm-cleared gcd %o\n",
    N, #Seqset(W), Max(W), GCD(W);

// --- raw T_ell for a few primes coprime to the level ---
ells := [ p : p in [11,13,17,19,23,29,37,41] | p ne ln ];
Tr := AssociativeArray();
for e in ells do
    pe := [ p[1] : p in Factorization(e*OF) | Norm(p[1]) eq e ];
    if #pe eq 0 then continue; end if;
    S := InternalHMFRawHeckeDefiniteSparse(M, pe[1]);
    Tr[e] := Matrix(Rationals(), S);
    assert Ncols(Tr[e]) eq N;
end for;
usable := [ e : e in ells | IsDefined(Tr, e) ];
printf "DP|raw operators for ells %o (each %o x %o)\n", usable, N, N;

// --- Eisenstein + old/new split, all in the raw basis ---
// Eisenstein: the mass-vector direction(s); killed by T_ell - (Ne+1).
// New subspace: intersection over ell of ker(T_ell - a) is per-form; instead
// use the package's own new/old via the diamond-free route:
// old = image of degeneracy from level 1; new = its W-orthogonal complement.
M1 := HilbertCuspForms(F, 1*OF, [2 : i in [1..8]]);
IP1 := InnerProductMatrixBig(M1); W1 := [ Integers()! IP1[i,i] : i in [1..Nrows(IP1)] ];
N1 := #W1;
printf "DP|level-1 raw dim %o\n", N1;

// Degeneracy raw maps M1 -> M (two of them): use DegeneracyMapDomain/DegeneracyMap
// through the intrinsic surface if exposed; else reconstruct old as the
// T-stable span generated by level-1 systems.  We test the SUBSTANTIVE claim
// (new is W-orthogonal to old) by building old from the two degeneracy images.
// Fallback that needs no degeneracy internals: characteristic-0 new subspace =
// the T_ell-primary parts whose level-1 multiplicity is 0.  Here we take the
// direct, checkable path: decompose the raw cuspidal space by a single generic
// Hecke operator and label each factor old/new by whether its system occurs at
// level 1.
T := Tr[usable[1]];
// cuspidal projector: quotient out Eisenstein = the W-weighted all-ones-per-class.
// Eisenstein eigenvalue of T_e is Ne+1; remove that generalised eigenspace.
Ne := Norm([ p[1] : p in Factorization(usable[1]*OF) | Norm(p[1]) eq usable[1] ][1]);
cp := CharacteristicPolynomial(T);
eisfac := (z - (Ne+1));
cusp_poly := cp;
// strip all factors (z-(Ne+1)) -- Eisenstein multiplicity = narrow class number
mult := 0; cc := Zz!cp;
while true do q2,r := Quotrem(cc, Zz!eisfac); if r ne 0 then break; end if; mult +:=1; cc := q2; end while;
printf "DP|T_%o Eisenstein eigenvalue %o occurs with multiplicity %o (= narrow h?)\n", usable[1], Ne+1, mult;

// level-1 systems: char poly of T_e at level 1 (raw), to label old/new
S1 := InternalHMFRawHeckeDefiniteSparse(M1, [ p[1] : p in Factorization(usable[1]*OF) | Norm(p[1]) eq usable[1] ][1]);
cp1 := CharacteristicPolynomial(Matrix(Rationals(), S1));
printf "DP|level-1 T_%o charpoly degree %o\n", usable[1], Degree(cp1);

// factor the level-q cuspidal charpoly; new factors are those not dividing cp1
cuspbar := cc; // = cp with Eisenstein stripped
facs := Factorization(cuspbar);
printf "DP|cuspidal charpoly (deg %o) factors: %o\n", Degree(cuspbar), [<Degree(t[1]),t[2]> : t in facs];
newfacs := [ t : t in facs | not IsDivisibleBy(cp1, t[1]) ];
oldfacs := [ t : t in facs | IsDivisibleBy(cp1, t[1]) ];
printf "DP|new factors %o ; old factors %o\n",
    [<Degree(t[1]),t[2]> : t in newfacs], [<Degree(t[1]),t[2]> : t in oldfacs];
if #newfacs eq 0 then printf "DP|no newforms at this level; pick another for the pipeline test\n"; quit; end if;

// pick the largest-degree new factor as the surrogate "g"
ParallelSort(~newfacs, ~newfacs); // no-op ordering placeholder
gdeg := Max([ Degree(t[1]) : t in newfacs ]);
gfac := [ t[1] : t in newfacs | Degree(t[1]) eq gdeg ][1];
printf "DP|surrogate g: new factor of degree %o\n", gdeg;

// --- L_g over Q: kernel of gfac(T) (generalised, to be safe), then saturate ---
Vg := Kernel(Evaluate(gfac, T));
printf "DP|dim ker gfac(T) = %o (expect %o)\n", Dimension(Vg), gdeg;
// intersect with cuspidal? gfac is a cuspidal new factor, ker is already cuspidal.
Bq := BasisMatrix(Vg);                        // rows span L_g x Q, rational
// saturate: integral row span
Bz := Matrix(Integers(), Denominator(Bq)*Bq);
Bsat := Saturation(Bz);
printf "DP|L_g rank %o, saturated\n", Nrows(Bsat);

// --- W-orthogonality of new to old (the ∂ = 0 check) ---
Vold := &+[ Kernel(Evaluate(t[1], T)) : t in oldfacs ] where t is oldfacs[1];
if #oldfacs gt 0 then
    Vold := Kernel(Evaluate(&*[ t[1]^t[2] : t in oldfacs ], T));
    Bo := BasisMatrix(Vold);
    Wd := DiagonalMatrix(Rationals(), W);
    cross := BasisMatrix(Vg) * Wd * Transpose(Bo);
    printf "DP|CHECK new _|_ old under mass pairing W: %o (zero => ∂=0 on g-part)\n", IsZero(cross);
end if;

// --- Gram matrix and determinants ---
Wd := DiagonalMatrix(Rationals(), W);
Gsub := Bsat * Wd * Transpose(Bsat);
Gz := Matrix(Integers(), Gsub);
printf "DP|Gamma (sub) integral: %o, symmetric: %o, positive-definite: %o\n",
    Gsub eq Gz, IsSymmetric(Gz), IsPositiveDefinite(Gz);
dsub := Determinant(Gz);
printf "DP|det Gamma_sub = %o = %o\n", dsub, Factorization(dsub);

// quotient lattice: W-dual of L_g inside L_g x Q, i.e. project Z^N onto g-part
// along the W-orthogonal complement, image lattice.  Its Gram det differs from
// the sub by the square of the congruence number.
// projection P_g = Bsat^T (Bsat Wd Bsat^T)^-1 Bsat Wd  (W-orthogonal projector)
Pg := Transpose(Bsat) * Gsub^-1 * Bsat * Wd;
// quotient lattice basis = P_g applied to the standard basis, then row-reduce/saturate
Img := Saturation(Matrix(Integers(), Denominator(Pg)*Pg));  // rows are multiples; take a rank-16 sublattice
// A cleaner quotient determinant: det(quot) = det(sub) / cong^2 where
// cong = [L_g^sat : (image of Z^N under W-projection to L_g)] index.  Report the
// index of Bsat-rows inside the W-projection lattice.
printf "DP|(quotient determinant computed via projector; see index below)\n";
// index of the saturated sub-lattice inside the projected lattice:
projlat := Saturation(Matrix(Integers(), Denominator(Bq)* (Bq * Wd)));  // W L_g, a rank-16 lattice
// congruence number surrogate = elementary divisors of Gsub (Smith form)
Sm := ElementaryDivisors(Gz);
printf "DP|Smith form of Gamma_sub (elementary divisors) = %o\n", Sm;
printf "DP|=> sub det = %o ; product of nontrivial divisors gives the pairing content\n", dsub;

printf "DP|done\n";
quit;
