

# This file was *autogenerated* from the file belyi/groups.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_8 = Integer(8); _sage_const_4 = Integer(4)# Milestone 3.3 (group driver): from a 2-group G and a monodromy triple, produce the
# tower skeleton -- a chief series G = H_0 > H_1 > ... > H_n = 1 (each index 2, each
# H_i normal in G so every X_i = Fix(H_i) is Galois over P^1) and, per level, the
# data the radicand solver needs.
#
# For a Galois intermediate X_i (H_i normal), the cover X_i -> P^1 has group G/H_i
# and passport = orders of the images of (s0,s1,sinf) in G/H_i.  The quadratic step
# X_{i+1}/X_i corresponds to the character chi_i: H_i/H_{i+1} = C_2, and over a branch
# point b it ramifies at a place Q (a double coset H_i g <sigma_b>) iff the inertia
# I_Q = H_i cap g<sigma_b>g^{-1} is NOT contained in H_{i+1}.

def chief_series_indices(G):
    """Chief series of the 2-group G as a descending list of subgroups, each index 2
    in the previous and normal in G.  (GAP ChiefSeries has C_2 factors for a 2-group.)"""
    cs = libgap.ChiefSeries(G)
    chain = [cs[k] for k in range(int(libgap.Length(cs)))]
    # ChiefSeries steps may have index >2 only if a chief factor is elementary abelian
    # of rank>1; refine those to index-2 normal steps.
    refined = [chain[_sage_const_0 ]]
    for k in range(_sage_const_1 , len(chain)):
        top, bot = refined[-_sage_const_1 ], chain[k]
        while int(libgap.Index(top, bot)) > _sage_const_2 :
            # find an index-2 subgroup M with bot <= M < top, normal in G
            found = None
            for cc in libgap.MaximalSubgroups(top):
                if libgap.IsSubgroup(cc, bot) and int(libgap.Index(top, cc)) == _sage_const_2                          and bool(libgap.IsNormal(G, cc)):
                    found = cc; break
            if found is None:      # fall back: any index-2 subgroup containing bot
                for cc in libgap.MaximalSubgroups(top):
                    if libgap.IsSubgroup(cc, bot) and int(libgap.Index(top, cc)) == _sage_const_2 :
                        found = cc; break
            refined.append(found); top = found
        refined.append(bot)
    return refined

def level_passport(G, s0, s1, H):
    """Passport (orders of s0,s1,sinf in G/H) of the Galois cover Fix(H) -> P^1."""
    sinf = (s0 * s1)**(-_sage_const_1 )
    q = libgap.NaturalHomomorphismByNormalSubgroup(G, H)
    return tuple(int(libgap.Order(libgap.Image(q, s))) for s in (s0, s1, sinf))

def ramifies_in_step(G, Hi, Hi1, g, sb):
    """Does X_{i+1}/X_i ramify at the place of X_i = Fix(Hi) given by double coset
    Hi.g.<sb>?  I_Q = Hi cap g<sb>g^{-1}; ramifies iff I_Q not subset Hi1."""
    cyc = libgap.Group(sb)
    conj = libgap.ConjugateSubgroup(cyc, g**(-_sage_const_1 ))     # g <sb> g^{-1}
    IQ = libgap.Intersection(Hi, conj)
    return not bool(libgap.IsSubgroup(Hi1, IQ))

def step_ramified_branch_points(G, Hi, Hi1, s0, s1, sinf):
    """Which of the three branch points {0,1,oo} does the step X_{i+1}/X_i ramify over?
    Chief factor Hi/Hi1 is central in G/Hi1, so chi_i is G-invariant and ramification
    over b is all-or-nothing: ramifies iff I_b = <sigma_b> cap Hi is NOT subset of Hi1."""
    out = []
    for name, sb in [('0', s0), ('1', s1), ('oo', sinf)]:
        Ib = libgap.Intersection(libgap.Group(sb), Hi)
        if not bool(libgap.IsSubgroup(Hi1, Ib)):
            out.append(name)
    return out

def tower_skeleton(G, s0, s1, verbose=True):
    chain = chief_series_indices(G)
    sinf = (s0 * s1)**(-_sage_const_1 )
    rows = []
    for i in range(len(chain) - _sage_const_1 ):
        Hi, Hi1 = chain[i], chain[i + _sage_const_1 ]
        pp_i = level_passport(G, s0, s1, Hi)
        # genus of X_i via the coset action (index [G:Hi])
        d = int(libgap.Index(G, Hi))
        rows.append((i, int(libgap.Order(Hi)), d, pp_i))
        if verbose:
            print(f"  level {i}: X_i=Fix(H_{i}) |H|={int(libgap.Order(Hi)):3d} "
                  f"deg[G:H]={d:3d} passport={pp_i}")
    if verbose:
        print(f"  top: X = Fix(1), degree {int(libgap.Order(G))}")
    return chain, rows

if __name__ == "__main__":
    G = libgap.SmallGroup(_sage_const_8 , _sage_const_4 )                        # Q8
    gens = libgap.GeneratorsOfGroup(G)
    s0, s1 = gens[_sage_const_0 ], gens[_sage_const_1 ]; sinf = (s0*s1)**(-_sage_const_1 )
    print("Q8 chief series + per-level passports:")
    chain, rows = tower_skeleton(G, s0, s1)
    print("per-step ramified branch points (radicand support):")
    for i in range(len(chain)-_sage_const_1 ):
        rb = step_ramified_branch_points(G, chain[i], chain[i+_sage_const_1 ], s0, s1, sinf)
        print(f"  step {i}->{i+_sage_const_1 }: ramifies over {rb}")

