

# This file was *autogenerated* from the file belyi/validate_q8.sage
from sage.all_cmdline import *   # import sage library

_sage_const_16 = Integer(16); _sage_const_5 = Integer(5); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1)# PIPELINE VALIDATION on a real thesis curve.
# Source: michaelmusty/2GroupDessins  TwoDBPassportChar0/8/8T5-4,4,4-g2.m
# The Q8 (=8T5) genus-2 Belyi map, passport (4,4,4), over Q(i):
#   F: y^8 + (1/2 x^3 - 3/2 x^2 + x) y^4 + (1/16 x^6 - 1/8 x^5 + 1/16 x^4) = 0,  phi = x.
#
# Group-theory PREDICTION (torsion_module.sage): Q8 acts on J[2]=F_2^4 through
# Q8/{+-1}=V4 (center acts trivially mod 2); centralizer = M_1(F_4), SOLVABLE.
# => Q(J[2]) must be solvable.
#
# Hand reduction of the tower (w=y^4 quadratic in x; s^2=1-x; U=u/(s(1+s)) rational):
#   disc_w = p^2-4q = -x^2 (x-1)^3,  and the genus-2 curve becomes hyperelliptic
#   y^2 = 16 m^5 - m = m (4m^2-1)(4m^2+1).
# Q(J[2]) = splitting field of that quintic.  This file VERIFIES the outcome.
from sage.all import QQ, PolynomialRing, HyperellipticCurve, NumberField

R = PolynomialRing(QQ, 'm'); m = R.gen()
f = _sage_const_16 *m**_sage_const_5  - m
C = HyperellipticCurve(f)
assert C.genus() == _sage_const_2 , C.genus()
assert f.discriminant().factor().unit() * _sage_const_1  and set(p for p, e in f.discriminant().factor()) == {_sage_const_2 },     f.discriminant().factor()                      # ramified only at 2 (disc = -2^20)
K = NumberField(R('m^2+1'), 'i')
splits = all(fac.roots(K) and sum(mult for _, mult in fac.roots(K)) == fac.degree()
             for fac, _ in f.factor())
assert splits, "quintic should split over Q(i)"
# => Q(J[2]) = Q(i), Galois group C_2, SOLVABLE, ramified only at 2.
print("Q8 8T5-444-g2:  hyperelliptic model y^2 =", f.factor())
print("  genus =", C.genus(), " disc =", f.discriminant().factor(), "(ramified only at 2)")
print("  Q(J[2]) = Q(i)  (splitting field of the quintic)  =>  Gal = C_2, SOLVABLE")
print("  MATCHES the group-theory prediction (Q8 centralizer M_1(F_4) solvable).")

